# Generated by Django 4.2.1 on 2023-07-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_food', '0002_light_normal_strong_superstrong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='light',
            name='description',
        ),
        migrations.RemoveField(
            model_name='normal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strong',
            name='description',
        ),
        migrations.RemoveField(
            model_name='superstrong',
            name='description',
        ),
    ]
