# Generated by Django 4.2.1 on 2023-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_food', '0003_remove_light_description_remove_normal_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
