# Generated by Django 4.2.1 on 2023-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_food', '0004_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='normal',
            name='description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='strong',
            name='description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='super',
            name='description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='superstrong',
            name='description',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
